/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

import java.util.*;

public class ProjectEulerProblem2
{
   public static void main(String[] args)
   {
      System.out.println ("Numbers are: " + fib(4000000));
   }

   public static double fib(int maxNumber)
   {
      if (maxNumber <= 1)
         return maxNumber;
      else
      {
         double answer = (fib (maxNumber - 1) + fib (maxNumber - 2));
         return answer;
      }
   }
}
